
pannous:
  file: programy.services.pannous
  class: PannousSRAIService

pandora:
  file: programy.services.pandora
  class: PandoraSRAIService

google:
  file: programy.services.google
  class: GoogleSRAIService

wikipedia:
  file: programy.services.wikipedia
  class: WikipediaSRAIService

generic:
  file: programy.services.generic
  class: GenericSRAIService
